base_encoder: resnet18
base_encoder_params: pretrained=False,spatial_dims=2,n_input_channels=4,num_classes=512
batch_size: 3
class_column: fsqc_qc
csv_test: /CMF/data/floda/abcd-data-release-5.1/QC_second/QC_DATA_train_fold0_test.csv
csv_train: /CMF/data/floda/abcd-data-release-5.1/QC_second/QC_DATA_train_fold0_train_train.csv
csv_valid: /CMF/data/floda/abcd-data-release-5.1/QC_second/QC_DATA_train_fold0_train_test.csv
dropout_lvl: 0.2
epochs: 200
fs_path: /CMF/data/floda/abcd-data-release-5.1/data
hidden_dim: 512
image_size: 128
layer: IcoConv2D
log_every_n_steps: 10
lr: 0.0001
mean: 0
model: null
mount_point: ./
neptune_project: null
neptune_tags: null
neptune_token: null
nn: SaxiRing
noise_lvl: 0.01
num_images: 12
num_workers: 4
out: /CMF/data/floda/abcd-data-release-5.1/test/results/train/fold0
out_classes: 2
out_size: 256
path_ico_left: ./3DObject/sphere_f327680_v163842.vtk
path_ico_right: ./3DObject/sphere_f327680_v163842.vtk
patience: 30
pretrained: false
profiler: null
radius: 1.1
scale_factor: 1.0
std: 0.005
subdivision_level: 3
surf_column: surf
tb_dir: null
tb_name: tensorboard
train_sphere_samples: 10000
