args: !!python/object:argparse.Namespace
  base_encoder: resnet18
  base_encoder_params: pretrained=False,n_input_channels=4,spatial_dims=2,num_classes=512
  batch_size: 60
  class_column: null
  csv_test: teeth-grand_challenge_vtk/test.csv
  csv_train: teeth-grand_challenge_vtk/train.csv
  csv_valid: teeth-grand_challenge_vtk/val.csv
  epochs: 200
  hidden_dim: 512
  image_size: 256
  log_every_n_steps: 10
  lr: 0.0001
  model: null
  mount_point: /work/floda/data/DCBIA/
  neptune_project: null
  neptune_tags: null
  nn: SaxiSegmentation
  num_workers: 16
  out: training_output/
  patience: 30
  profiler: null
  radius: 1.35
  scale_factor: null
  subdivision_level: 1
  surf_column: surf
  tb_dir: tensorboard/
  tb_name: flyby
  train_sphere_samples: 4
class_weights: null
image_size: 320
out_channels: 34
radius: 1.35
subdivision_level: 1
train_sphere_samples: 4
