base_encoder: resnet18
base_encoder_params: pretrained=False,spatial_dims=2,n_input_channels=4,num_classes=512
batch_size: 3
class_column: fsqc_qc
csv_test: /CMF/data/floda/abcd-data-release-5.1/QC_second/QC_DATA_train_fold0_test.csv
csv_train: /CMF/data/floda/abcd-data-release-5.1/QC_second/QC_DATA_train_fold0_train_train.csv
csv_valid: /CMF/data/floda/abcd-data-release-5.1/QC_second/QC_DATA_train_fold0_train_test.csv
dropout_lvl: 0.2
epochs: 200
fs_path: /CMF/data/floda/abcd-data-release-5.1/data
hidden_dim: 512
image_size: 128
log_steps: 20
logger: USAEReconstructionNeptuneLogger
lr: 0.0001
model: null
monitor: null
mount_point: ./
neptune_tags: null
nn: SaxiRing
num_workers: 4
out: /CMF/data/floda/abcd-data-release-5.1/test/results/train/fold0
out_classes: 2
out_size: 256
patience: 30
radius: 1.1
steps: -1
subdivision_level: 3
surf_column: surf_path
use_early_stopping: 0
