base_encoder: resnet18
base_encoder_params: pretrained=False,spatial_dims=2,n_input_channels=4,num_classes=512
batch_size: 3
class_column: class
crown_segmentation: false
csv_test: /work/floda/data/DCBIA/teeth_data/challenge_teeth_all_train_fold0_test.csv
csv_train: /work/floda/data/DCBIA/teeth_data/challenge_teeth_all_train_fold0_train_train.csv
csv_valid: /work/floda/data/DCBIA/teeth_data/challenge_teeth_all_train_fold0_train_test.csv
epochs: 20
hidden_dim: 512
image_size: 256
log_every_n_steps: 10
lr: 0.0001
mean: 0
model: null
monitor: null
mount_point: /work/floda/data/DCBIA/teeth_data/
neptune_project: null
neptune_tags: null
neptune_token: null
nn: SaxiSegmentation
num_images: 12
num_workers: 4
out: /work/floda/data/DCBIA/teeth_data/train/fold0
out_channels: 4
patience: 30
radius: 1.5
scale_factor: 1.0
std: 0.005
steps: -1
subdivision_level: 2
surf_column: surf
tb_dir: null
tb_name: tensorboard
use_early_stopping: 0
