base_encoder: resnet18
base_encoder_params: pretrained=False,spatial_dims=2,n_input_channels=4,num_classes=512
batch_size: 2
class_column: fsqc_qc
csv_test: /CMF/data/floda/QC_DATA_1_TO_1_train_fold0_test.csv
csv_train: /CMF/data/floda/QC_DATA_1_TO_1_train_fold0_train_train.csv
csv_valid: /CMF/data/floda/QC_DATA_1_TO_1_train_fold0_train_test.csv
dropout_lvl: 0.2
epochs: 30
fs_path: /CMF/data/floda/abcd_filtered
hidden_dim: 512
image_size: 256
layer: IcoConv2D
log_every_n_steps: 10
lr: 0.0001
mean: 0
model: null
monitor: null
mount_point: ./
neptune_project: null
neptune_tags: null
neptune_token: null
nn: SaxiIcoClassification_fs
num_images: 12
num_workers: 4
out: /CMF/data/floda/data_files_4feat_check/train/fold0
out_classes: 2
out_size: 256
patience: 30
radius: 1.5
scale_factor: 1.0
std: 0.005
steps: -1
subdivision_level: 2
surf_column: surf
tb_dir: null
tb_name: tensorboard
use_early_stopping: 0
